rabbitmq1:
  image: cbirajdar/rabbitmq
  hostname: node1
  ports:
    - "5672:5672"
    - "15672:15672"
rabbitmq2:
  image: cbirajdar/rabbitmq
  hostname: node2
  ports:
    - "5673:5672"
    - "15673:15672"
  environment:
    - CLUSTER_WITH=node1
